### ISSUE TITLE
CSC OBS unresolvable and Circle CI package deployment

### ISSUE THREAD

**Issue by JacobJoseph-gu** [WarwickMicroscopy/Felix#156]
We have uploaded felix as a tar.bz2 to OBS but it is not building correctly.
https://obs.csc.warwick.ac.uk/package/show/warwick.ac.uk:Physics:Felix/felix?expand=1

We are interested in systems: centOS, SUSE, ubunutu

Circle CI 1.0 deployment pages:
- Continuous Deployment with Google Container Engine
https://circleci.com/docs/1.0/continuous-deployment-with-google-container-engine/
- Pushing packages to packagecloud
https://circleci.com/docs/1.0/pushing-packages-to-packagecloud/

We could use packagecloud with RPMBUILD or DEBUILD
https://packagecloud.io/docs#how_to_create_packages

It seems that we could do any custom deployment including pushing to CSC OBS
```
deployment:
  prod:
    branch: master
    commands:
      - ./deploy.sh
```

Circle CI 2.0 deployment looks particularly capable:
```
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              <your-deploy-commands>
            fi
```

https://wiki.debian.org/Packaging/Intro?action=show&redirect=IntroDebianPackaging
https://fedoraproject.org/wiki/How_to_create_an_RPM_package
https://github.com/obspy/obspy/wiki/Installation-on-Linux-via-RPM-Repository#install-obspy
https://gist.github.com/fernandoaleman/1377211

**Comment by JacobJoseph-gu** [comment]
I am going to work on deploying packages. Are we happy with circle CI or do we want to look into alternatives?

We are currently using circle CI 1.0, which tests on an Ubuntu (14.04 Trusty) machine, which is an older version to the Ubuntu machines we primarily use (16.04).
To my knowledge, we cannot setup circle CI to attempt an openSUSE build (the OS used on the CSC machines. We can specify different compiler options in Ubuntu (mpifort, ifort etc.), which is useful. We should also be able to automatically deploy RPMs and DEBIAN packages for various systems including openSUSE and ubuntu. It is a shame not being able to automatiucally build on openSUSE before deploing a package for it. Is this a big deal?

**Comment by rbeanland** [comment]
Hi Jacob,
I managed to unlock my access to CircleCI through GitHub, but the description of what it does makes very little sense to me.  I am mainly concerned with getting the physics right and being able to use the code to extract useful/interesting information from materials. I am not really interested in the computing details or what platforms it runs on, as long as it works. I am not yet convinced that there is any potential user base who would take advantage of the things you are talking about.

Please bear in mind that if I don't find these tools useful I am unlikely to use them, and will carry on developing the software without them. So I am happy with whatever decision you make (as long as it doesn't get in the way of the main point of the exercise)!

Richard

On 10 Sep 2017, at 16:31, JacobJoseph-gu <notifications@github.com<mailto:notifications@github.com>> wrote:


I am going to work on deploying packages. Are we happy with circle CI or do we want to look into alternatives?

We are currently using circle CI 1.0, which tests on an Ubuntu (14.04 Trusty) machine, which is an older version to the Ubuntu machines we primarily use (16.04).
To my knowledge, we cannot setup circle CI to attempt an openSUSE build (the OS used on the CSC machines. We can specify different compiler options in Ubuntu (mpifort, ifort etc.), which is useful. We should also be able to automatically deploy RPMs and DEBIAN packages for various systems including openSUSE and ubuntu. It is a shame not being able to automatiucally build on openSUSE before deploing a package for it. Is this a big deal?

**Comment by RudoRoemer** [comment]
CircleCI in V2 is now working again. Is the deployment is still of interest, please get in touch. Otherwise, I am closing this issue now.
