### ISSUE TITLE
Setting IRefineModeFLAG=S causes error 

### ISSUE THREAD

**Issue by dnjohnstone** [WarwickMicroscopy/Felix#188]
Setting IRefineModeFLAG=S in the SrTiO3_short sample causes the following error in writing outputs. I believe this is that it tries to write a new structure factor output, but it hasn't calculated one with this flag.

     -----------------------------------------------------------------
     felixrefine: 'Version: master / 1.03 / r.beanland               '
                  'Date: 14-Mar-2019                                 '
                  'Refinements B,C,D,F,H and S working, no HOLZ      '
     -----------------------------------------------------------------
     total number of MPI ranks  001, screen messages via rank 000
     -----------------------------------------------------------------
     Reflection pool of  600 with a minimum of   50 strong beams
     Material: SrTiO3, P m -3 m
     Simulation only
     Mean inner potential  22.42 Volts
     325 unique structure factors
     Starting absorption calculation...
     Absorption    0 hrs   0 mins   9 sec
     Bloch wave calculation...
     Simulation    0 hrs   3 mins   1 sec
     Writing simulations for   1 thicknesses
     At line 488 of file write_output_mod.f90
     Fortran runtime error: Index '1' of dimension 1 of array 'iindependentvariabletype' above upper bound of 0

     Error termination. Backtrace:
     #0  0x7fb745ece8da
     #1  0x7fb745ecf395
     #2  0x7fb745ecf73a
     #3  0x564000509ac2
     #4  0x5640004cd0e4
     #5  0x5640004b469e
     #6  0x7fb745b05b16
     #7  0x5640004b46c9
     #8  0xffffffffffffffff

**Comment by RudoRoemer** [comment]
This was part of the errors emerging from compiling with the gfortran compiler. Should now be fixed.
